---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Install terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - uses: UCL-MIRSG/.github/actions/linting@49c9af6b750d9de3bbdcb3cbba3806c96bc3b486 # v0
        with:
          ansible-roles-config: ./modules/k3s-cluster/provision/ansible/requirements.yaml
          pre-commit-config: ./.pre-commit-config.yaml
